FROM python

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./main.py /app/main.py
COPY ./start.sh /app/start.sh

ENTRYPOINT ["bash", "start.sh"]
CMD ["0.0.0.0", "8080"]
