apiVersion: batch/v1
kind: Job
metadata:
  name: poller
spec:
  template:
    spec:
      containers:
      - name: poller
        image: byrnedo/alpine-curl
        command: ["echo $(/bin/sh -c curl -s http://${SERVER_SERVICE_SERVICE_HOST}:${SERVER_SERVICE_SERVICE_PORT}/time)"]
      restartPolicy: Never
  backoffLimit: 4

# apiVersion: v1
# kind: Pod
# metadata:
#   name: poller
# spec:
#   containers:
#   - name: poller
#     image: cherrygender/poller:0.0.5
#     volumeMounts:
#       - name: log-volume
#         mountPath: /logs
#   volumes:
#   - name: log-volume
#     hostPath:
#       path: /logs
#       type: DirectoryOrCreate

